# Generated by Django 5.2.3 on 2025-06-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanPendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, help_text='Aktifkan untuk membuka pendaftaran siswa baru')),
            ],
        ),
    ]
