# Generated by Django 5.2.3 on 2025-06-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nisn', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('nik', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=20)),
                ('asal_sekolah', models.CharField(max_length=255)),
                ('alamat_asal_sekolah', models.TextField()),
                ('nama_ayah', models.CharField(max_length=255)),
                ('nama_ibu', models.CharField(max_length=255)),
                ('no_telepon_ortu', models.CharField(max_length=20)),
                ('dok_kk', models.FileField(upload_to='dokumen/kk/')),
                ('dok_akte', models.FileField(upload_to='dokumen/akte/')),
                ('dok_ijazah', models.FileField(upload_to='dokumen/ijazah/')),
                ('dok_ktp_ortu', models.FileField(upload_to='dokumen/ktp_ortu/')),
                ('dok_kip', models.FileField(blank=True, null=True, upload_to='dokumen/kip/')),
            ],
        ),
    ]
