# Generated by Django 5.2.3 on 2025-06-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(choices=[('X', 'Kelas X'), ('XI', 'Kelas XI'), ('XII', 'Kelas XII')], default='X', max_length=5),
            preserve_default=False,
        ),
    ]
