# Generated by Django 5.2.3 on 2025-06-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profil/'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(choices=[('X', 'Kelas X'), ('XI', 'Kelas XI'), ('XII', 'Kelas XII')], default='X', max_length=5),
        ),
    ]
