# Generated by Django 5.2.3 on 2025-06-26 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_siswa_foto_profil_alter_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siswa',
            name='dok_akte',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/akte/'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='dok_ijazah',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/ijazah/'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='dok_kk',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/kk/'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='dok_ktp_ortu',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/ktp_ortu/'),
        ),
    ]
