# Generated by Django 5.2.3 on 2025-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0004_siswa_created_at_alter_siswa_dok_akte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('LULUS', 'Lulus'), ('PINDAH', 'Pindah'), ('DROPOUT', 'Drop Out')], default='AKTIF', max_length=10),
        ),
    ]
