# Generated by Django 5.2.3 on 2025-06-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0006_alter_siswa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[('BARU', 'Murid Baru'), ('AKTIF', 'Aktif'), ('LULUS', 'Lulus'), ('PINDAH', 'Pindah'), ('DROPOUT', 'Drop Out')], default='BARU', max_length=10),
        ),
    ]
