# Generated by Django 5.2.3 on 2025-06-27 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_profil', models.ImageField(blank=True, default='foto_profil_admin/default.jpg', null=True, upload_to='foto_profil_admin/')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('BENDAHARA', 'Bendahara'), ('KEPALA_SEKOLAH', 'Kepala Sekolah')], default='ADMIN', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
